application: population-centers-in-disaster
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media
  
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: .*
  script: main.py

